"""Convert the statistical_inference submodule's notebooks to Markdown references.

Reads every .ipynb in src/databy_ai_mcp/core/statistical_inference/ and writes a
corresponding Markdown file (plus any extracted image resources) into that same
submodule's references/ subdirectory, stamped with provenance (source repo,
commit, original notebook path) pulled live from the submodule's own git metadata
so the output always points back at exactly what it was generated from.

Usage:
    uv run --group docs python scripts/notebooks_to_md.py
"""

from __future__ import annotations

import subprocess
from datetime import datetime, timezone
from pathlib import Path

from nbconvert import MarkdownExporter
from nbconvert.writers import FilesWriter
from traitlets.config import Config

ROOT = Path(__file__).resolve().parent.parent
SUBMODULE_DIR = ROOT / "src" / "databy_ai_mcp" / "core" / "statistical_inference"
REFERENCES_DIR = SUBMODULE_DIR / "references"


def _git(*args: str) -> str:
    return subprocess.run(
        ["git", "-C", str(SUBMODULE_DIR), *args],
        check=True,
        capture_output=True,
        text=True,
    ).stdout.strip()


def _submodule_provenance() -> dict[str, str]:
    return {
        "remote_url": _git("remote", "get-url", "origin"),
        "commit": _git("rev-parse", "HEAD"),
        "branch": _git("rev-parse", "--abbrev-ref", "HEAD"),
        "commit_date": _git("show", "-s", "--format=%ci", "HEAD"),
    }


def _front_matter(notebook_path: Path, provenance: dict[str, str]) -> str:
    rel_path = notebook_path.relative_to(SUBMODULE_DIR)
    blob_url = (
        provenance["remote_url"].removesuffix(".git")
        + f"/blob/{provenance['commit']}/{rel_path.as_posix()}"
    )
    generated_at = datetime.now(timezone.utc).isoformat(timespec="seconds")
    return (
        "---\n"
        f"source_repo: {provenance['remote_url']}\n"
        f"source_commit: {provenance['commit']}\n"
        f"source_branch: {provenance['branch']}\n"
        f"source_path: {rel_path.as_posix()}\n"
        f"source_url: {blob_url}\n"
        f"generated_at: {generated_at}\n"
        "generated_by: scripts/notebooks_to_md.py\n"
        "---\n\n"
        f"> Converted from [`{rel_path.as_posix()}`]({blob_url}) in "
        f"[{provenance['remote_url']}]({provenance['remote_url']}) "
        f"at commit `{provenance['commit'][:12]}`. Edit the notebook in the "
        "submodule, not this file — re-run `scripts/notebooks_to_md.py` to "
        "refresh it.\n\n"
    )


def convert_all() -> list[Path]:
    provenance = _submodule_provenance()
    REFERENCES_DIR.mkdir(parents=True, exist_ok=True)

    config = Config()
    config.MarkdownExporter.exclude_input_prompt = True
    exporter = MarkdownExporter(config=config)
    writer = FilesWriter(build_directory=str(REFERENCES_DIR))

    written: list[Path] = []
    for notebook_path in sorted(SUBMODULE_DIR.glob("*.ipynb")):
        stem = notebook_path.stem
        # output_files_dir must be set before rendering, not after — the
        # template resolves each image's link path (and the
        # ExtractOutputPreprocessor its written filename) from this key at
        # render time, scoping images per notebook so cell-count-based names
        # like output_4_0.png can't collide across notebooks.
        body, resources = exporter.from_filename(
            str(notebook_path), resources={"output_files_dir": f"{stem}_files"}
        )
        body = _front_matter(notebook_path, provenance) + body
        writer.write(body, resources, notebook_name=stem)
        written.append(REFERENCES_DIR / f"{stem}.md")

    _write_index(written, provenance)
    return written


def _write_index(written: list[Path], provenance: dict[str, str]) -> None:
    lines = [
        "# Statistical Inference — Converted References\n",
        "\n",
        "Markdown copies of the notebooks in this submodule, regenerated by "
        "`scripts/notebooks_to_md.py`. Treat these as read-only derivatives — "
        "the notebooks (`.ipynb`) in the parent directory are the source of "
        "truth.\n",
        "\n",
        f"- **Source repository:** {provenance['remote_url']}\n",
        f"- **Pinned commit:** `{provenance['commit']}` ({provenance['commit_date']})\n",
        f"- **Branch:** `{provenance['branch']}`\n",
        "\n",
        "## Contents\n",
        "\n",
    ]
    for path in written:
        title = path.stem.split("_", 1)[-1].replace("-", " ").title()
        lines.append(f"- [{path.stem} — {title}]({path.name})\n")

    (REFERENCES_DIR / "README.md").write_text("".join(lines))


if __name__ == "__main__":
    for path in convert_all():
        print(f"wrote {path.relative_to(ROOT)}")
